changelog:
  categories:
    - title: å·²å®Œæˆçš„åŠŸèƒ½ ğŸ‰
      labels:
        - GitHub Package Action
        - å¼€æœºè‡ªå¯è®¾ç½®
        - ç›‘æµ‹åœ¨æ¸¸æˆå†…ç¦ç”¨Winé”®
        - æ—¥å¿—ç•Œé¢

    - title: 1.0.1ç‰ˆæœ¬çš„è®¡åˆ’ ğŸ› 
      labels:
        - å¢åŠ  qqæ¶ˆæ¯ç›‘å¬
        - GitHub Page å¥åº·æ£€æŸ¥
        - è½¯ä»¶è‡ªåŠ¨æ›´æ–°
